apiVersion: apps/v1
kind: Deployment
metadata:
  name: crypto-exchange-fe-new
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crypto-exchange-fe
  template:
    metadata:
        labels:
          app: crypto-exchange-fe
          version: "0.2"
    spec:
      containers:
        - image: bitvavo/k8s-canary-app:v0.2
          imagePullPolicy: IfNotPresent
          name: crypto-exchange-fe-new
          ports:
            - name: fe-port
              containerPort: 80
          resources: {}

