apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
nodes:
  - role: control-plane
  - role: worker
    extraPortMappings:
      - containerPort: 5678 # internal loadbalancer port for app
        hostPort: 5678 # port exposed on "host" machine to access app