apiVersion: v1
kind: Service
metadata:
  labels:
    name: crypto-exchange-fe
  name: crypto-exchange-fe
spec:
  ports:
    - name: crypto-exchange-fe
      port: 31080
      targetPort: 80
      nodePort: 31080
  type: NodePort
  selector:
    app: crypto-exchange-fe